"""Crop white padding off the AI-generated PNGs and downscale to 16x16 (nearest-neighbor)
so they read as crisp 16x16 Minecraft block textures.

Inputs (high-res, generated by GenerateImage tool):
    {ASSETS}/assembler_top_hires.png
    {ASSETS}/assembler_side_hires.png
    {ASSETS}/assembler_bottom_hires.png

Outputs (final, dropped into the mod's textures folder):
    src/main/resources/assets/hidechunk/textures/blocks/ultimate_assembler_top.png
    src/main/resources/assets/hidechunk/textures/blocks/ultimate_assembler_side.png
    src/main/resources/assets/hidechunk/textures/blocks/ultimate_assembler_bottom.png
"""
from __future__ import annotations
import os
import sys
from PIL import Image

ASSETS = r"C:\Users\vinic\.cursor\projects\c-Users-vinic-Desktop-COREMOD-HIDE-CHUNK\assets"
OUT_DIR = r"src\main\resources\assets\hidechunk\textures\blocks"
TARGET = 16

# Pixels brighter than this on all RGB channels are considered "padding".
WHITE_THRESHOLD = 235


def detect_content_bbox(img: Image.Image) -> tuple[int, int, int, int]:
    """Return the bounding box of the non-padding region. Falls back to the full image."""
    rgb = img.convert("RGB")
    w, h = rgb.size
    px = rgb.load()
    min_x, min_y, max_x, max_y = w, h, -1, -1
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            if r < WHITE_THRESHOLD or g < WHITE_THRESHOLD or b < WHITE_THRESHOLD:
                if x < min_x:
                    min_x = x
                if y < min_y:
                    min_y = y
                if x > max_x:
                    max_x = x
                if y > max_y:
                    max_y = y
    if max_x < 0:
        return 0, 0, w, h
    return min_x, min_y, max_x + 1, max_y + 1


def square_bbox(bbox: tuple[int, int, int, int], img_size: tuple[int, int]) -> tuple[int, int, int, int]:
    """Expand bbox to a centered square so we don't squash the texture."""
    x0, y0, x1, y1 = bbox
    w = x1 - x0
    h = y1 - y0
    if w == h:
        return bbox
    side = max(w, h)
    cx = (x0 + x1) // 2
    cy = (y0 + y1) // 2
    half = side // 2
    iw, ih = img_size
    sx0 = max(0, cx - half)
    sy0 = max(0, cy - half)
    sx1 = min(iw, sx0 + side)
    sy1 = min(ih, sy0 + side)
    sx0 = max(0, sx1 - side)
    sy0 = max(0, sy1 - side)
    return sx0, sy0, sx1, sy1


def process(src: str, dst: str) -> None:
    img = Image.open(src).convert("RGBA")
    bbox = detect_content_bbox(img)
    bbox = square_bbox(bbox, img.size)
    cropped = img.crop(bbox)
    # Step 1: downscale aggressively with LANCZOS to preserve pixel art structure.
    intermediate = cropped.resize((TARGET * 4, TARGET * 4), Image.LANCZOS)
    # Step 2: final reduction to TARGET with NEAREST so output stays crisp.
    final = intermediate.resize((TARGET, TARGET), Image.NEAREST)
    final = final.convert("RGB")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    final.save(dst, format="PNG", optimize=True)
    print(f"  cropped {bbox} -> {dst}")


def main() -> int:
    pairs = [
        ("assembler_top_hires.png", "ultimate_assembler_top.png"),
        ("assembler_side_hires.png", "ultimate_assembler_side.png"),
        ("assembler_bottom_hires.png", "ultimate_assembler_bottom.png"),
    ]
    for src_name, dst_name in pairs:
        src = os.path.join(ASSETS, src_name)
        dst = os.path.join(OUT_DIR, dst_name)
        if not os.path.exists(src):
            print(f"missing source: {src}", file=sys.stderr)
            return 1
        print(f"processing {src_name}")
        process(src, dst)
    return 0


if __name__ == "__main__":
    sys.exit(main())
